### ISSUE TITLE
Active Node TRUST-IN-XDC-PS stuck in PROPOSED after REBOOT

### ISSUE THREAD

**Issue by presman** [XinFinOrg/MasterNode-App#2]
Hello Team, My TRUST-IN-XDC-PS mainnet node was successfully running and earning rewards daily from June 2 to June 16th. After the xdc.log file got over 45 gig in size, I shut it down, deleted the log file, rebooted my server and restarted the master node. After 2 hours, it went green and appears to be running on the #stats page.

However, this node stopped earning rewards after the reboot, is stuck in "PROPOSED" status and has not randomly been selected for any verifications since the reboot on June 16th (7 days). This is not normal as the system should be randomly selecting it throughout the day.

The only possible disconnect that I can think of is the coinbase.txt address, which has been setup like this since the go-live on June 2nd:

Master Node coinbase.txt file address (default on installation of MN code):
 xdcxdcc67c2dec79da735d6587d8db3c23271d557196ab

MN candidate coinbase.txt address was entered as (WITHOUT Duplicate xdcxdc....)
 xdcc67c2dec79da735d6587d8db3c23271d557196ab

I noticed the MN code was updated a few days ago but I have not run update.sh yet.

Can you help me determine why this mainnet node stopped working after the June 16th reboot and delete of xdc.log file?

Thank you again for all of your help!
Preston

**Comment by AnilChinchawale** [comment]
Please check now and let us know current status.

**Comment by presman** [comment]
Hello Anil - Yes, the MN is in the group of 18 for verifications now, it is showing as "Masternode" status and also receiving rewards to the account.

Can you confirm if the root cause has been fixed so anyone can reboot and if all approved master nodes are being considered for the random 18 selection every 1-2 epochs?

Thank you for all of your help!
Preston
